apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencast-data-pv-claim
  namespace: opencast
  labels:
    edu.my.srv: opencast
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
